#lang sicp

; Exercise: Give interpretation of stream generated by this procedure

(define (expand num den radix)
    (cons-stream
        (quotient (* num radix) den)
        (expand (remainder (* num radix) den) den radix)))


; The stream is a result of division of 
; number num*radix by den
; where radix is also determines the accuracy of operation
; if radix is 1 then result should be integer
; if radix is 10 then result have accuracy of 10^-1
; if radix is 100 then result have accuracy of 100^-1
; and so on